/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import static interfaces.CreateLoginInterface.socket;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author gustavo
 */
public class PatientMenuInterface extends javax.swing.JFrame {
    public static String response = new String("");
    private static InputStream inputStream2;
    private static OutputStream outputStream2;
    private static DataInputStream dint2;
    private static DataOutputStream dout2;
    public static Socket socket2 = CreateLoginInterface.socket;
    /**
     * Creates new form signUp
     */
    public PatientMenuInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        form = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Welcome!");

        form.setText("Complete Formulary");
        form.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formActionPerformed(evt);
            }
        });

        jButton1.setText("Add EMG");

        jButton2.setText("Add ECG");

        jButton3.setText("Search EMG by date");

        jButton4.setText("Search ECG by date");

        jButton5.setText("Change Username");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Change Password");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Go back");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(form)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton4)
                            .addComponent(jButton5)
                            .addComponent(jButton6)
                            .addComponent(jButton7))))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(form)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formActionPerformed
        try {
            // TODO add your handling code here:
            
            outputStream2 = socket2.getOutputStream();
            dout2 = new DataOutputStream(outputStream2);
            inputStream2 = socket2.getInputStream();                
            dint2 = new DataInputStream(inputStream2);
            int entero = 1;
            dout2.writeInt(entero);
            Formulary form = new Formulary(this,true);
            form.setVisible(true);
            dout2.writeUTF(response);
            String okay = dint2.readUTF();
            
            if (okay == "Form saved successfully" ){
                PatientMenuInterface p = new PatientMenuInterface();
                JOptionPane.showMessageDialog(p, "Form saved successfully!");
                
            }
            else {
                PatientMenuInterface p = new PatientMenuInterface();
                JOptionPane.showMessageDialog(p, "Form can't be saved!");
            }
        } catch (IOException ex) {
            Logger.getLogger(PatientMenuInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        CreateLoginInterface c = new CreateLoginInterface();
        this.setVisible(false);
        c.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            // TODO add your handling code here:
            outputStream2 = socket2.getOutputStream();
            dout2 = new DataOutputStream(outputStream2);
            inputStream2 = socket2.getInputStream();
            dint2 = new DataInputStream(inputStream2);
            int entero = 5;
            dout2.writeInt(entero);
            String okay;
            String username2 = JOptionPane.showInputDialog("Introduce your new Username");
            dout2.writeUTF(username2);
            okay = dint2.readUTF();
            if (okay.equals("Action Completed")){
                PatientMenuInterface p = new PatientMenuInterface();
                JOptionPane.showMessageDialog(p, "Action completed!");
            } else {
                PatientMenuInterface p = new PatientMenuInterface();
                JOptionPane.showMessageDialog(p, "Can not be completed!");
            }
        } catch (IOException ex) {
            Logger.getLogger(PatientMenuInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            // TODO add your handling code here:
            outputStream2 = socket2.getOutputStream();
            dout2 = new DataOutputStream(outputStream2);
            inputStream2 = socket2.getInputStream();
            dint2 = new DataInputStream(inputStream2);
            int entero = 6;
            dout2.writeInt(entero);
            String okay;
            String password = JOptionPane.showInputDialog("Introduce your new Password");
            dout2.writeUTF(password);
            okay = dint2.readUTF();
            if (okay.equals("Action Completed")){
                PatientMenuInterface p = new PatientMenuInterface();
                JOptionPane.showMessageDialog(p, "Action completed!");
            } else {
                PatientMenuInterface p = new PatientMenuInterface();
                JOptionPane.showMessageDialog(p, "Can not be completed!");
            }
        } catch (IOException ex) {
            Logger.getLogger(PatientMenuInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        

            try {
                /* Set the Nimbus look and feel */
                //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
                * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                */
                try {
                    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Nimbus".equals(info.getName())) {
                            javax.swing.UIManager.setLookAndFeel(info.getClassName());
                            break;
                        }
                    }
                } catch (ClassNotFoundException ex) {
                    java.util.logging.Logger.getLogger(PatientMenuInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    java.util.logging.Logger.getLogger(PatientMenuInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    java.util.logging.Logger.getLogger(PatientMenuInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                    java.util.logging.Logger.getLogger(PatientMenuInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                //</editor-fold>
                //</editor-fold>
                
                
                outputStream2 = socket2.getOutputStream();
                
                inputStream2 = socket2.getInputStream();
                
                dint2 = new DataInputStream(inputStream2);
                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        new PatientMenuInterface().setVisible(true);
                    }
                });
                
            } catch (IOException ex) {
                Logger.getLogger(PatientMenuInterface.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton form;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
